export const resume = {
    heading: "Resume",
    "quote": " Education is such a weapon by which we can change the world, by NELSON MANDELA",
    "bio":  "•Junior Web developer with an extensive educational and working knowledge of software, Web database development with a variety of tools and programming languages.\n•Skilled at writing well-designed, testable, and efficient codes using current best practices in Web development.\n•Strong experience in client interaction and understanding business application, business data flow and data relations from them.\n•Proficient in all phases of SDLC(analysis, design, development, testing and deployment) and highly competent in  gathering user requirements.\n•Experience in development methodologies like Agile, waterfall and Interactive life cycle and software engineering processes.\n•Experience in writing database objects like Stored Procedures, Triggers, PL/SQL packages and cursors for Oracle, MySQL.\n•Committed to excellence, self-motivator, fast learner, hard worker, and team player ability to deal with people and a sprudent developer with strong problem-solving skills and communication skills.",
    "skills" : "TECHNICAL SKILLS \n\n•Web Technologies - HTML5, CSS3, XML, CSS Grid, HTTP,Bootstrap4, JavaScript, TypeScript, JSON, RESTful APIs,Agile, Scrum, Waterfall, Unit- Testing, GIT, SASS and AJAX and HTTP semantics \n•JavaScript Technologies - jQuery, React, React-Redux,AngularJs, Angular2+, Material-UI, and Express JS\n•Application Software - JIRA and Confluence\n•Package/Tools - MS Office, Visual Studio, Eclipse,Sublime Text, and Lotus Notes.\n•UI Designing Tools - Adobe Photoshop and AdobeXD.\n• Content Management System – WordPress",
    "experience": "EXPERIENCE  \n\n2019/08 – PRESENT\nFRONT END DEVELOPER, INSYGHT.AI, OAKVILLE, ON\n\n• Hands-on experience in creating highly interactive single-page applications using ReactJS and Angular framework that respond to all user actions.\n• Responsible for creating end-to-end restful API for uploading/fetching files to platforms for file storage such as AWS.\n•Collaborated and communicated with backend developers and quality analysts for integration and testing.\n• Worked with agile methodologies, CI/CD practice, and software tools such as JIRA, Jenkins, Git, Maven, and popular IDEs.\n•Used Git for version control, Jira fro tracking work in the workplace.\n•Provide workflow to improve code quality through peer code reviews and feedback.",
    "experience2": "2018/10 – 2019/08\nFULL STACK WEB DEVELOPER, FREELANCER\n\n•As a programmer and freelance developer, I focused on code maintenance, debugging and performance. Worked heavily on HTML, CSS, JavaScript, MySQL, Nodejs, Reactjs.\n•Worked on a wide variety of projects including UI/UX design layouts, design web applications from scratch and debugging and testing using the latest technology, thus refining development skills.\n•Developed websites and landing pages for small businesses such as restaurants, interior designers, fashion designers.\n•Used-various tools to develop and troubleshooting issues on client's websites.\n•Created front end user interfaces for various projects as well as manage real-time database",
    "experience3": "2018/05 – 2018/09\nTECHNICAL & OFFICE SUPPORT, DREAM BIG TRANSPORTATION\n\n• Effectively worked under pressure to balance inbound calls from drivers and assist in problem-solving any issues they encountered (e.g. Route review, etc.).\n• Organized workflow and effectively communicated with all team members and assist associates in ways that optimize procedures.\n• Prepared and submitted a professional performance report on the business monthly.",
    "education": "EDUCATION \n\n2017 – 2018\nMASTER OF ENGINEERING IN COMPUTER ENGINEERING, UNIVERSITY OF WINDSOR (GPA- 3.7)\n\n\n2012 - 2016\nBACHELOR OF COMPUTER SCIENCE, GURU NANAK DEV UNIVERSITY, AMRITSAR-PUNJAB, INDIA (GPA-3.6).",
    "activity": "ACTIVITIES\n\nVolunteer:\nEvents Coordinator of the UWindsor Sikh Society\nPublic Relations Executive of the Indian Student Association at UWindsor"
 
    
    
 

}